<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0">
  <channel>
    <title>OpenAI 开发者论坛 - 最新帖子</title>
    <link>https://community.openai.com</link>
    <description>最新帖子</description>
    <lastBuildDate>Tue, 05 Mar 2024 03:20:35 GMT</lastBuildDate>
    <item>
      <title>审核端点返回不够配额</title>
      <link>https://community.openai.com/t/moderations-endpoint-returns-insufficient-quota/530625#post_11</link>
      <description><![CDATA[开发团队是否有关于配额不足消息的最新消息？]]></description>
      <guid>https://community.openai.com/t/moderations-endpoint-returns-insufficient-quota/530625#post_11</guid>
      <pubDate>Tue, 05 Mar 2024 03:17:58 GMT</pubDate>
    </item>
    <item>
      <title>与 API 迁移和配额错误作斗争</title>
      <link>https://community.openai.com/t/struggling-with-the-api-migration-and-quota-errors/666066#post_5</link>
      <description><![CDATA[当然 - 感谢您的帮助 - 我在 12 月底编写了一个完整的 gpt 应用程序，该应用程序与数据库和所有内容交互，然后在假期休息了一会儿，当我回来时，我无法完成任何工作。&lt; /p&gt;
&lt;小时/&gt;
C:\Users\frank&gt;C:/Users/frank/AppData/Local/Programs/Python/Python311/python.exe “c:/Users/frank/Documents/My-Python/test lab/hello chat world .py”
回溯（最近一次调用最后一次）：
文件“c:\Users\frank\Documents\My-Python\test lab\hello chat world.py”，第 4 行，位于 
完成 = client.chat.completions.create(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
文件“C:\Users\frank\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai_utils_utils.py”，第 275 行，包装器
返回 func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^
文件“C:\Users\frank\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\resources\chat\completions.py”，第 663 行，在 create
返回 self._post(
^^^^^^^^^^^
文件“C:\Users\frank\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai_base_client.py”，第 1200 行，在帖子
返回cast（ResponseT，self.request（cast_to，opts，stream=stream，stream_cls=stream_cls））
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ^^^^^^^^^^^^^^^^
文件“C:\Users\frank\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai_base_client.py”，第 889 行，请求中
返回 self._request(
^^^^^^^^^^^^^^^
文件“C:\Users\frank\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai_base_client.py”，第 965 行，在 _request
返回 self._retry_request(
^^^^^^^^^^^^^^^^^^^^^
文件“C:\Users\frank\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai_base_client.py”，第 1013 行，在 _retry_request
返回 self._request(
^^^^^^^^^^^^^^^
文件“C:\Users\frank\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai_base_client.py”，第 965 行，在 _request
返回 self._retry_request(
^^^^^^^^^^^^^^^^^^^^^
文件“C:\Users\frank\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai_base_client.py”，第 1013 行，在 _retry_request
返回 self._request(
^^^^^^^^^^^^^^^
文件“C:\Users\frank\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai_base_client.py”，第 980 行，在 _request
从 None 引发 self._make_status_error_from_response(err.response)
openai.RateLimitError：错误代码：429 - {‘error’：{‘message’：‘您超出了当前配额，请检查您的计划和账单详细信息。了解更多信息
关于此错误，请阅读文档：https://platform.openai.com/docs/guides/error-codes/api-errors.&#39;, &#39;type&#39;: &#39;insufficient_quota&#39;, &#39;param&#39;: None, &#39;code&#39;: &#39;insufficient_quota&#39;}}]]></description>
      <guid>https://community.openai.com/t/struggling-with-the-api-migration-and-quota-errors/666066#post_5</guid>
      <pubDate>Tue, 05 Mar 2024 03:15:47 GMT</pubDate>
    </item>
    <item>
      <title>我被禁止了，我不知道为什么</title>
      <link>https://community.openai.com/t/i-am-banned-and-i-have-no-idea-why/665420#post_4</link>
      <description><![CDATA[是的，退款就像对他们进行欺诈以导致帐户被禁止一样。




API 密钥被盗，丢失费用为 $ ，支持人员没有回复 社区&lt; /跨度&gt;

  &lt;块引用&gt;
    我强烈建议不要遵循“让信用卡公司处理”的建议，这本质上相当于发起商户退款。如果您重视与 OpenAI 的关系或希望将来使用他们的 API，那么了解商家通常对退款持相当不利的态度至关重要。
  
]]></description>
      <guid>https://community.openai.com/t/i-am-banned-and-i-have-no-idea-why/665420#post_4</guid>
      <pubDate>Tue, 05 Mar 2024 03:15:02 GMT</pubDate>
    </item>
    <item>
      <title>与 API 迁移和配额错误作斗争</title>
      <link>https://community.openai.com/t/struggling-with-the-api-migration-and-quota-errors/666066#post_4</link>
      <description><![CDATA[


 CyborgPrime：
&lt;块引用&gt;
刚刚支付了我的账单 - 全部都是最新的


仍然无法工作？你能显示它返回的错误吗？]]></description>
      <guid>https://community.openai.com/t/struggling-with-the-api-migration-and-quota-errors/666066#post_4</guid>
      <pubDate>Tue, 05 Mar 2024 03:10:46 GMT</pubDate>
    </item>
    <item>
      <title>与 API 迁移和配额错误作斗争</title>
      <link>https://community.openai.com/t/struggling-with-the-api-migration-and-quota-errors/666066#post_3</link>
      <description><![CDATA[开放AI库：版本：1.13.3
Python 3.11
我在 API 文档中找到的这段代码：
从 openai 导入 OpenAI
客户端 = OpenAI()
完成 = client.chat.completions.create(
型号=“gpt-3.5-turbo”，
消息=[
{“role”: “system”, “content”: “你是一位诗意的助手，擅长以创造性的天赋解释复杂的编程概念。”},
{“role”: “user”, “content”: “写一首诗来解释编程中的递归概念。”}
]
）
打印(completion.choices[0].message)
&lt;小时/&gt;
刚刚支付了我的账单 - 全部都是最新的]]></description>
      <guid>https://community.openai.com/t/struggling-with-the-api-migration-and-quota-errors/666066#post_3</guid>
      <pubDate>Tue, 05 Mar 2024 03:09:46 GMT</pubDate>
    </item>
    <item>
      <title>与 API 迁移和配额错误作斗争</title>
      <link>https://community.openai.com/t/struggling-with-the-api-migration-and-quota-errors/666066#post_2</link>
      <description><![CDATA[我们很乐意提供帮助，但我们需要更多信息。
您使用什么库？代码？型号？
账单是最新的吗？信用卡附上吗？提前购买积分？]]></description>
      <guid>https://community.openai.com/t/struggling-with-the-api-migration-and-quota-errors/666066#post_2</guid>
      <pubDate>Tue, 05 Mar 2024 03:00:54 GMT</pubDate>
    </item>
    <item>
      <title>[Bug] 助手运行步骤/消息 API 无法正常工作</title>
      <link>https://community.openai.com/t/bug-assistant-run-steps-message-api-is-not-working-correctly/655009#post_2</link>
      <description><![CDATA[对这里的问题表示歉意 - 我们刚刚解决了这个问题。如果您再次看到此内容，请告诉我们。]]></description>
      <guid>https://community.openai.com/t/bug-assistant-run-steps-message-api-is-not-working-correctly/655009#post_2</guid>
      <pubDate>Tue, 05 Mar 2024 02:59:06 GMT</pubDate>
    </item>
    <item>
      <title>GPT-4-0125-预览幻觉工具调用</title>
      <link>https://community.openai.com/t/gpt-4-0125-preview-hallucinating-tool-calls/609610#post_4</link>
      <description><![CDATA[今天也点击这个。希望这是一些间歇性问题，OpenAI 很快就能解决？]]></description>
      <guid>https://community.openai.com/t/gpt-4-0125-preview-hallucinating-tool-calls/609610#post_4</guid>
      <pubDate>Tue, 05 Mar 2024 02:52:58 GMT</pubDate>
    </item>
    <item>
      <title>在 chat.completion 中使用相同的提示时，Logprobs 不断变化</title>
      <link>https://community.openai.com/t/logprobs-keep-changing-when-using-the-same-prompt-in-chat-completion/665669#post_4</link>
      <description><![CDATA[不。您将看到在 softmax 之后模型内部完成的计算结果。 OpenAI 尚未说明这是软件还是硬件，并且很可能没有人能够从架构上了解原因并对此做出回答。]]></description>
      <guid>https://community.openai.com/t/logprobs-keep-changing-when-using-the-same-prompt-in-chat-completion/665669#post_4</guid>
      <pubDate>Tue, 05 Mar 2024 02:46:24 GMT</pubDate>
    </item>
    <item>
      <title>Gpt4 聊天已中断数周</title>
      <link>https://community.openai.com/t/gpt4-chat-broken-for-several-weeks/618281#post_5</link>
      <description><![CDATA[已经26天了，还没修好。真的越来越垃圾了]]></description>
      <guid>https://community.openai.com/t/gpt4-chat-broken-for-several-weeks/618281#post_5</guid>
      <pubDate>Tue, 05 Mar 2024 02:41:58 GMT</pubDate>
    </item>
    </channel>
</rss>